---
services:
  haproxy:
    build:
      context: ./infrastructure/load_balancer
      dockerfile: Dockerfile.dev
    container_name: haproxy
    ports:
      - "60000-60001:60000-60001"
    networks:
      - expensify_network
    depends_on:
      - web-a
      - web-b

  web-a:
    build:
      context: ./infrastructure/web_server
      dockerfile: Dockerfile.dev
    container_name: web-a
    environment:
      MESSAGE: "Web Server: A"
    ports:
      - "5001:5001"
    networks:
      - expensify_network

  web-b:
    build:
      context: ./infrastructure/web_server
      dockerfile: Dockerfile.dev
    container_name: web-b
    environment:
      MESSAGE: "Web Server: B"
    ports:
      - "5002:5002"
    networks:
      - expensify_network

  nagios:
    image: jasonrivers/nagios:latest
    container_name: nagios
    ports:
      - "8080:80"
    environment:
      - NAGIOS_TIMEZONE=UTC
    volumes:
      - ./infrastructure/nagios/etc:/opt/nagios/etc/
      - ./infrastructure/nagios/libexec:/opt/nagios/libexec/
    restart: always
    networks:
      - expensify_network

  mkdocs:
    container_name: mkdocs
    image: squidfunk/mkdocs-material
    ports:
      - "8000:8000"
    volumes:
      - ./mkdocs:/docs

networks:
  expensify_network:
    driver: bridge
    name: expensify_network