FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN pip install flask python-dotenv gunicorn

EXPOSE 80

# Set the environment to production and use Gunicorn
ENV FLASK_ENV=production
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:80", "app:app"]
