---
site_name: Project Documentation
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
nav:
  - Project Overview: index.md
  - Getting Started: getting_started.md
  - Docker: docker.md
  - Services:
      - Web Servers: webserver.md
      - Load Balancer: loadbalancer.md
      - Nagios: nagios.md
  - About: about.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
